### ISSUE TITLE
GitHub Commit Message Rule 

### ISSUE THREAD

**Issue by karistin** [DonghoOh-pipity03/2022_KPU_CE_Shotfire#18]
https://jason-api.tistory.com/89

---
<summary>

FEAT : 새로운 기능의 추가
FIX: 버그 수정
DOCS: 문서 수정
STYLE: 스타일 관련 기능(코드 포맷팅, 세미콜론 누락, 코드 자체의 변경이 없는 경우)
REFACTOR: 코드 리펙토링
TEST: 테스트 코트, 리펙토링 테스트 코드 추가
CHORE: 빌드 업무 수정, 패키지 매니저 수정(ex .gitignore 수정 같은 경우

type(타입) : title(제목)

body(본문, 생략 가능)

Resolves : #issue, ...(해결한 이슈 , 생략 가능)

See also : #issue, ...(참고 이슈, 생략 가능)

</summary>

**Comment by karistin** [comment]
확인후 코멘트 남기기!

**Comment by getchan0119** [comment]
확인

**Comment by DonghoOh-pipity03** [comment]
확인
