### ISSUE TITLE
escRoom()

### ISSUE THREAD

**Issue by DonghoOh-pipity03** [DonghoOh-pipity03/2022_KPU_CE_Shotfire#26]
@getchan0119 
develop에서 새로운 브랜치  만들어서 작업할것
게임룸에서 나갈때 구현 및 게임 종료 구현 

~ 3/21

**Comment by getchan0119** [comment]
https://github.com/DonghoOh-pipity03/2022_KPU_CE_Shotfire/commit/e8a6be12456914b1d3b354a98ac0898348ff7144
