### ISSUE TITLE
Delete Character with photon

### ISSUE THREAD

**Issue by DonghoOh-pipity03** [DonghoOh-pipity03/2022_KPU_CE_Shotfire#35]
마지막 스테이지 종료시, '캐릭터 삭제' 코드 작성 요청

[마지막 스테이지에서 게임 종료시 남아있는 캐릭터]
![화면 캡처 2022-03-22 122549](https://user-images.githubusercontent.com/87480099/159401994-2bf4034d-14d8-48dc-91d4-359f9e283588.jpg)

[추가 작성해야 할 코드 위치]
![화면 캡처 2022-03-22 122628](https://user-images.githubusercontent.com/87480099/159402038-0b212fe6-1357-48c3-8ede-22a0aefacda0.jpg)

**Comment by karistin** [comment]
#50  완료
